# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-15 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=200)),
                ('message_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
