apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: ui-point
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 8050
    targetPort: 8050
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: ui-point
      tier: frontend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: ui-point
        tier: frontend
        track: stable
    spec:
      containers:
      - name: test-dash
        image: test-front
        imagePullPolicy: Never
#        lifecycle:
#          preStop:
#            exec:
#              command: ["/usr/sbin/nginx","-s","quit"]