apiVersion: v1
kind: Pod
metadata:
  name: first-test-pod
  labels:
    app: web
spec:
  containers:
    - name: test-rest
      image: test-api
      imagePullPolicy: Never
      ports:
        - containerPort: 8000
    - name: test-dash
      image: test-front
      imagePullPolicy: Never
      ports:
        - containerPort: 80
---
kind: Service
metadata:
  name: hello
spec:
  selector:
    app: hello
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: http