apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: api-point
    tier: backend
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: api-point
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: api-point
        tier: backend
        track: stable
    spec:
      containers:
      - name: test-rest
        image: test-api
        imagePullPolicy: Never
#        lifecycle:
#          preStop:
#            exec:
#              command: ["/usr/sbin/nginx","-s","quit"]