# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-23 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meetups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetup_name', models.CharField(max_length=200)),
                ('meetup_address', models.CharField(max_length=1000)),
                ('meetup_time', models.DateTimeField()),
                ('meetup_locationx', models.FloatField()),
                ('meetup_locationy', models.FloatField()),
            ],
        ),
    ]
